const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Plugins.Camera3D,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.EightDir,
		C3.Behaviors.Rotate,
		C3.Plugins.gamepad,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY
	];
};
self.C3_JsPropNameTable = [
	{Room: 0},
	{"3DCamera": 0},
	{Tween: 0},
	{PlayerBillboard: 0},
	{Keyboard: 0},
	{PlayerShadow: 0},
	{Trap: 0},
	{Spike: 0},
	{Solid: 0},
	{Collision: 0},
	{Flash: 0},
	{Arrow: 0},
	{PlayerAnimations: 0},
	{"8Direction": 0},
	{PlayerCollision: 0},
	{Rotate: 0},
	{Gem: 0},
	{Smoke: 0},
	{GemShadow: 0},
	{Pillar: 0},
	{Gamepad: 0},
	{GalaxyBillboard: 0},
	{Wall01: 0},
	{Wall04: 0},
	{Wall02: 0},
	{Wall03: 0},
	{GalaxyTexture: 0},
	{Tutorial: 0},
	{DificultyLevel: 0},
	{Direction: 0},
	{Lifespan: 0}
];

self.InstanceType = {
	Room: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	PlayerBillboard: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	Trap: class extends self.I3DShapeInstance {},
	Spike: class extends self.I3DShapeInstance {},
	Collision: class extends self.ITilemapInstance {},
	Arrow: class extends self.ISpriteInstance {},
	PlayerAnimations: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Gem: class extends self.I3DShapeInstance {},
	Flash: class extends self.I3DShapeInstance {},
	Smoke: class extends self.I3DShapeInstance {},
	GemShadow: class extends self.ISpriteInstance {},
	Pillar: class extends self.I3DShapeInstance {},
	Gamepad: class extends self.IInstance {},
	GalaxyBillboard: class extends self.I3DShapeInstance {},
	Wall01: class extends self.I3DShapeInstance {},
	Wall04: class extends self.I3DShapeInstance {},
	Wall02: class extends self.I3DShapeInstance {},
	Wall03: class extends self.I3DShapeInstance {},
	GalaxyTexture: class extends self.ITiledBackgroundInstance {},
	Tutorial: class extends self.ISpriteFontInstance {}
}